version: '3.5'


services:

  database:
    container_name: database
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    image: postgres:15.3-alpine

  app:
    container_name: app
    ports:
      - '8000:8000'
    build: ./backend
    depends_on:
      - database
  